### ISSUE TITLE
Error: Segmentation fault

### ISSUE THREAD

**Issue by OleksandrBlack** [team-exor/generic-seeder#1]
```
https://github.com/Fair-Exchange/safecoin
```
settings.conf
```
protocol_version="170022"
init_proto_version="212"
min_peer_proto_version="170020"
caddr_time_version="31402"
pchMessageStart_0 = "0xf1"
pchMessageStart_1 = "0xed"
pchMessageStart_2 = "0xe2"
pchMessageStart_3 = "0x8f"
wallet_port="8770"
explorer_url="https://explorer.deepsky.space/api/getblockcount"
second_explorer_url="https://explorer.deepsky.space/api/getblockcount"
explorer_requery_seconds="60" 
block_count="10"
seed_1="dnsseed.local.support"
seed_2="dnsseed.fair.exchange"
seed_3="explorer.safecoin.org"
seed_4="66.42.45.93"
seed_5="173.199.119.93"
seed_6="164.68.119.151"
seed_7="93.170.147.127"
seed_8="207.180.239.247"
seed_9="45.76.165.17"
seed_10="45.77.220.43"
```

```
./dnsseed -h dnsseedua.local.support -n seedvpsua.local.support -m m@m.com
```

**Comment by joeuhren** [comment]
Hey, thanks for reporting the issue, I just noticed it today however. Apparently github doesn't send notifications regarding issues by default. Sorry about that.

I was able to find and fix the source of the problem. I haven't upgraded my dev tools in a long while and it appears that some compiler behavior was changed in recent versions which made the issue more apparent. Go ahead and grab an updated copy of the code and you should be able to run it without errors now.

I also have a few suggestions regarding your config:

1. You have specified the same api url for both the 1st and 2nd explorers which is not necessary and will only put additional load on that api server. Both explorer url values are optional. The reason for having the 2nd explorer url is as a backup, just in case the 1st explorer goes offline for some reason.

2. The explorer url you have provided is behind a firewall (cloudflare) and therefore is somewhat useless in this case because the seeder cannot get to the actual api data. Cloudflare offers the ability to exclude certain urls using wildcards, so if you have control over the explorer website, I would strongly recommend opening up the api calls so that they are not behind a firewall as this makes the data difficult to get to automatically.

3. Just a final note: The `-m m@m.com` part of your cmd is not necessary and can be omitted. It is only used to return an email address from the DNS record if desired. Either put a real email address or just remove that part of the cmd since I'm guessing you don't actually own the address m@m.com :)
