### ISSUE TITLE
n/n available, but seeder not working  

### ISSUE THREAD

**Issue by jaehyunh1** [team-exor/generic-seeder#15]
Hi, I'm trying to make a seeder of my own in Bitcoin regtest mode.

I followed your guides in Local DNS Server Setup, and the seeder seems to work well; it tracked all n nodes in my regtest network and marked n/n available (All the nodes were well listed in dnsseed.dump).

However, when I try to make a new node to join the network and fetch the address from this seeder, it doesn't work. The A record of the nameserver also doesn't appears in whatsmydns or nslookup.

What could be a problem here?

**Comment by joeuhren** [comment]
It sounds like either you made a mistake setting up the DNS entries or else your registrar is blocking certain ports or functionality. Did you have any problems creating the A and NS records? I've noticed that some registrars do not allow you to create NS records, so perhaps this is the problem in your case. Please share more information about how you set those DNS entries up, with screenshots if possible. If all else fails, you can always try cloudflare mode which should work regardless of any potential limitations from your registrar

**Comment by jaehyunh1** [comment]
I purchased a domain from godaddy, and there were no problems creating A and NS records. The value of A record (The IP where seeder app is running) is set as IP of my AWS EC2 instance. nslookup-ing the nameserver in the EC2 instance fails; it says server can't find due to SERVFAIL.

**Comment by jaehyunh1** [comment]
+) Of course, port 53 is opened here.

**Comment by joeuhren** [comment]
I've not personally used godaddy for this process, so it may be possible that they are doing something on their end to block this type of DNS set up. The only registrar I've used myself is namecheap and it works 100% right away. There was a recent example where someone contacted me privately and was having similar issues to yours with a different registrar. Everything seemed to be set up correctly from what I could tell but it just wouldn't work. In the end, I got them to create a new domain on namecheap and they were able to get the seeder working within minutes after that. We never did figure out what the problem was with the other registrar, only that it "just didn't work", even after contacting support many times.

At this point I see 3 options for getting this working:

1) If you are 100% sure you got your DNS entries set up correctly, try contacting godaddy support to see if they can find an issue or tell you there is something being blocked on their end, etc and hopefully unblock it for you. I'm not sure how much help this will be though since this type of seeder set up is rare/uncommon, but may be worth a shot if they can help you find an issue on their end that you may not normally be able to see on your end.

2) If you are only using your domain for the dns seeder, the easiest option would be to set up a free cloudflare account and set up your domain with them. Follow the steps from the dns seeder guide and you're done.

3) Try registering a new domain on namecheap.com. You can find domains for as little as $1-2 a year (sampledomain.cfd for example) which should hopefully not be too expensive for you to use as a test. I know for a fact that namecheap doesn't block anything in their DNS and the seeder will work 100% there. If you are able to do this test and get it working, but not with godaddy, then that will at least prove that there is something wrong on the godaddy end, in which case you can either continue trying to work out the problem with godaddy support or else transfer your domain to namecheap where you know this process is working,

Let us know how it works out.

**Comment by jaehyunh1** [comment]
The second option with cloudflare setups worked! I found out that the third option (with namecheap) also works as well.
Thank you so much for the feedbacks.

**Comment by joeuhren** [comment]
Glad to hear you got it working! More investigation may need to be done in the future to see if there is a way to determine what is being blocked by godaddy, and whether it is possible to unblock the connection somehow. But for now, there are other workarounds which will have to suffice.

I am closing this issue as resolved.
